### ISSUE TITLE
Version 0.8.12 breaks python3 CI builds

### ISSUE THREAD

**Issue by stephenpascoe** [gabrielfalcao/HTTPretty#278] opened 2015-12-15 16:43 UTC
Release 0.8.12 broke our Travis-CI setup because of the syntax error fixed in c54e09b521.  Could you cut a new PyPI release to fix?

**Comment by ebolyen** [comment] 2015-12-16 20:20
:+1: We are having the same issue in `scikit-bio` https://github.com/biocore/scikit-bio/pull/1242

**Comment by piskvorky** [comment] 2015-12-17 00:10
Same in https://github.com/piskvorky/smart_open/pull/46 -- please fix.

**Comment by bluszcz** [comment] 2015-12-20 15:22
Hi, I want to use httpretty for unittest https://github.com/VeggieSailor/vegbasket but it crashes with python 3.4:
```
======================================================================
ERROR: vegbasketapp.personal.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: vegbasketapp.personal.tests
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/bluszcz/dev/repo/vegbasket/vegbasketapp/vegbasketapp/personal/tests.py", line 9, in <module>
    from httpretty import HTTPretty
  File "/home/bluszcz/dev/pythons/VeggieSailor/lib/python3.4/site-packages/httpretty/__init__.py", line 30, in <module>
    from .core import httpretty, httprettified, EmptyRequestHeaders
  File "/home/bluszcz/dev/pythons/VeggieSailor/lib/python3.4/site-packages/httpretty/core.py", line 885
    key=lambda (matcher, _): matcher.priority,
               ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
```

**Comment by esc** [comment] 2015-12-21 12:12
Do you need any help to fix this? It is quite urgent, because all of our builds are breaking right now.

**Comment by esc** [comment] 2015-12-21 12:20
I tried downgrading to 0.8.11 but that one is broken too?

**Comment by Rovanion** [comment] 2015-12-27 22:46
Pinning version 8.10 as mentioned in issue #269 will get your tests running again, it's a temporary fix for your tests until the issue is fixed in some future release of httpretty, perhaps by you yourselves.

**Comment by snordhausen** [comment] 2015-12-28 11:11
The issue was already fixed with https://github.com/gabrielfalcao/HTTPretty/commit/c54e09b521be20139bf505694ec8b469d8e39059. All we need now is a new release.

**Comment by gabrielfalcao** [comment] 2016-01-18 13:56
closed by 354b6b7de9257be54283a1012e5f4a16963575cf

**Closed by gabrielfalcao** 2016-01-18 13:56 UTC

**Comment by esc** [comment] 2016-01-18 14:05
yay!

**Comment by esc** [comment] 2016-01-18 14:12
So travis was green on our latest build, i.e. I can confirm this works.

https://travis-ci.org/ImmobilienScout24/pybuilder_aws_plugin/builds/103115255
